// SPDX-License-Identifier: Apache-2.0
/**
 * Generate the dependency review sheet.
 *
 * `severedBy` is the weakest part of this project. Every invalidation result —
 * and therefore the whole claim that reassessment can be targeted rather than
 * total — rests on which change kinds sever which dependency edges. Those
 * mappings are judgement calls. They have never been reviewed by anyone with
 * domain authority, and until they are, "selective re-assurance" is a
 * plausible mechanism resting on unexamined assumptions.
 *
 * The obstacle to review has been that checking them meant reading TypeScript.
 * This emits a sheet a security or assurance reviewer can mark up directly,
 * generated from the code so it cannot drift from what actually executes.
 *
 * The third table is the important one. An edge severed by too many change
 * kinds is merely wasteful — it triggers reassessment nobody needed. An edge
 * severed by too few is dangerous: evidence stays valid when it should not,
 * and the permit keeps authorising on a basis that has quietly expired.
 * Errors of omission are the asymmetric risk, so the omissions get their own
 * table rather than being left for a reviewer to notice.
 *
 * Run: npx tsx ./cli/dependency-review.ts [--out docs/dependency-review.md]
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import {
  EXAMPLE_CLAIMS,
  EXAMPLE_EDGES,
  EXAMPLE_ARGUMENT_LAYER,
  CHANGE_DOMAIN,
  type MaterialChangeKind,
  type ChangeDomain,
} from '../src/index.ts';

const claimByRef = new Map(EXAMPLE_CLAIMS.map((c) => [c.ref, c]));
const ALL_KINDS = Object.keys(CHANGE_DOMAIN) as MaterialChangeKind[];

function domainOf(kind: MaterialChangeKind): ChangeDomain {
  return CHANGE_DOMAIN[kind];
}

/** Claim a supporting edge ultimately lands on, following claim→claim links. */
function terminalClaims(ref: string, seen = new Set<string>()): string[] {
  if (seen.has(ref)) return [];
  seen.add(ref);
  if (claimByRef.has(ref)) return [ref];
  const onward = EXAMPLE_EDGES.filter((e) => e.sourceRef === ref);
  return [...new Set(onward.flatMap((e) => terminalClaims(e.targetRef, seen)))];
}

const lines: string[] = [];
const p = (s = '') => lines.push(s);

p('<!-- SPDX-License-Identifier: CC-BY-4.0 -->');
p('<!-- GENERATED by cli/dependency-review.ts — do not edit by hand. -->');
p('# Dependency review sheet');
p();
p('**Generated:** ' + new Date().toISOString().slice(0, 10) +
  ' · **Edges:** ' + EXAMPLE_EDGES.length +
  ' · **Claims:** ' + EXAMPLE_CLAIMS.length +
  ' · **Change kinds:** ' + ALL_KINDS.length);
p();
p('## Why this document exists');
p();
p('Decirance claims that when an agent changes, only part of its assurance');
p('case needs reassessing, and that the part can be derived rather than');
p('guessed. That derivation runs entirely on the `severedBy` sets below: the');
p('change kinds that break each dependency between a piece of evidence and the');
p('claim it supports.');
p();
p('**These sets are judgement calls, and they have not been externally');
p('reviewed.** They were authored alongside the engine, not validated by');
p('anyone with authority over the security or assurance domain. Every');
p('invalidation result the tool produces inherits their correctness. This is');
p('the single largest unexamined assumption in the project, and it is stated');
p('here rather than left for a reviewer to discover.');
p();
p('## How to review this');
p();
p('For each row in table 1, ask one question:');
p();
p('> *If this change happened and nothing else did, would I still accept this');
p('> evidence as support for this claim?*');
p();
p('If yes, the change kind should **not** be in the set. If no, it should be.');
p('Table 3 lists the cases where the answer is currently "yes, still accepted"');
p('for a change in the same domain — the places an error of omission would');
p('hide.');
p();
p('Errors in the two directions are not symmetric:');
p();
p('- **Too many** severing kinds costs wasted reassessment. Annoying, safe.');
p('- **Too few** means evidence stays valid when it should not, and the permit');
p('  keeps authorising against a case that has quietly stopped holding. This is');
p('  the direction that causes harm.');
p();
p('So a reviewer in doubt should err toward adding a change kind.');
p();

// ── Table 1 ────────────────────────────────────────────────────────────────
p('## 1. Every dependency and what breaks it');
p();
p('| # | Evidence | Relation | Claim | Claim statement | Severed by | Agree? |');
p('|---|---|---|---|---|---|---|');
EXAMPLE_EDGES.forEach((e, i) => {
  const claim = claimByRef.get(e.targetRef);
  const statement = claim ? claim.statement : '—';
  const crit = claim?.critical ? ' **[critical]**' : '';
  const kinds = e.severedBy.length > 0
    ? e.severedBy.map((k) => `\`${k}\``).join('<br>')
    : '**(nothing)**';
  p(`| ${i + 1} | ${e.sourceRef} | ${e.kind} | ${e.targetRef}${crit} | ${statement} | ${kinds} | |`);
});
p();
p('The **Agree?** column is deliberately empty. It is for the reviewer.');
p();

const unsevered = EXAMPLE_EDGES.filter((e) => e.severedBy.length === 0);
if (unsevered.length > 0) {
  p('> **' + unsevered.length + ' edge(s) are severed by nothing at all.** Those');
  p('> dependencies survive every change this taxonomy can classify, which is a');
  p('> strong claim and should be challenged first:');
  p('>');
  for (const e of unsevered) p(`> - ${e.sourceRef} → ${e.targetRef}`);
  p();
}

// ── Table 2 ────────────────────────────────────────────────────────────────
p('## 2. Inverse index: if this changes, what is affected');
p();
p('The question a reviewer usually arrives with. Read a row and ask whether');
p('the claim list matches what you would expect that change to disturb — and');
p('in particular whether anything obvious is missing from it.');
p();
p('| Change kind | Domain | Edges severed | Claims reached |');
p('|---|---|---|---|');
for (const kind of ALL_KINDS) {
  const severed = EXAMPLE_EDGES.filter((e) => e.severedBy.includes(kind));
  const claims = [...new Set(severed.flatMap((e) => terminalClaims(e.targetRef)))].sort();
  const claimCell = claims.length > 0
    ? claims.map((c) => (claimByRef.get(c)?.critical ? `**${c}**` : c)).join(', ')
    : '_nothing_';
  p(`| \`${kind}\` | ${domainOf(kind)} | ${severed.length} | ${claimCell} |`);
}
p();
p('Bold claim references are critical claims. A change kind reaching **no**');
p('claims is either genuinely irrelevant to this case or a gap — the reference');
p('agent is narrow, so both are possible, and only a reviewer can say which.');
p();

const orphanKinds = ALL_KINDS.filter(
  (k) => !EXAMPLE_EDGES.some((e) => e.severedBy.includes(k)),
);
if (orphanKinds.length > 0) {
  p('> **' + orphanKinds.length + ' of ' + ALL_KINDS.length + ' change kinds sever nothing in this case:**');
  p('> ' + orphanKinds.map((k) => `\`${k}\``).join(', '));
  p('>');
  p('> The taxonomy is deliberately wider than the reference agent, so some of');
  p('> these are expected. Any that a reviewer thinks *should* bite here is a');
  p('> finding.');
  p();
}

// ── Table 3 ────────────────────────────────────────────────────────────────
p('## 3. The omissions worth challenging');
p();
p('For each edge, the change kinds **in the same assurance domain as something');
p('that already severs it** which nonetheless leave it standing. If a change');
p('is close enough to matter for one reason, it is worth asking why a sibling');
p('change does not.');
p();
p('This table is generated by a crude heuristic, not by insight. It is a');
p('reading order, not a list of defects.');
p();
p('| # | Edge | Already severed by domain(s) | Same-domain kinds that do NOT sever it |');
p('|---|---|---|---|');
let rows = 0;
EXAMPLE_EDGES.forEach((e, i) => {
  if (e.severedBy.length === 0) return;
  const domains = new Set(e.severedBy.map(domainOf));
  const candidates = ALL_KINDS.filter(
    (k) => domains.has(domainOf(k)) && !e.severedBy.includes(k),
  );
  if (candidates.length === 0) return;
  rows++;
  p(`| ${i + 1} | ${e.sourceRef} → ${e.targetRef} | ${[...domains].join(', ')} | ${candidates.map((k) => `\`${k}\``).join(', ')} |`);
});
p();
p(`${rows} edge(s) listed.`);
p();

// ── Assumptions ────────────────────────────────────────────────────────────
p('## 4. Assumptions, which sever the same way');
p();
p('Assumptions in the argument layer carry `severedBy` exactly as edges do,');
p('and they need the same review. An assumption that silently stops holding is');
p('how a case rots with every artefact still in date: the tests pass, the');
p('evidence is current, and the reasoning it supported no longer stands.');
p();
p('| Assumption | Statement | Status | Owner | Severed by |');
p('|---|---|---|---|---|');
for (const a of EXAMPLE_ARGUMENT_LAYER.assumptions) {
  p(`| ${a.ref} | ${a.statement} | ${a.status} | ${a.owner} | ${a.severedBy.map((k) => `\`${k}\``).join(', ') || '_nothing_'} |`);
}
p();
p('## What a completed review looks like');
p();
p('Not a sign-off. A marked-up copy of table 1 with disagreements noted, plus');
p('an answer on the omissions in table 3. Disagreements are more useful than');
p('agreement: a reviewer who changes one `severedBy` set has improved every');
p('invalidation result the tool will ever produce for that dependency.');
p();
p('Send findings to <https://github.com/Decirance/decirance/issues> or open a');
p('pull request against `src/example-case.ts`.');

const outIndex = process.argv.indexOf('--out');
const out = resolve(outIndex >= 0 ? process.argv[outIndex + 1] : 'docs/dependency-review.md');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join('\n') + '\n');
console.log(`Wrote ${out}`);
console.log(`  ${EXAMPLE_EDGES.length} edges, ${ALL_KINDS.length} change kinds, ${EXAMPLE_ARGUMENT_LAYER.assumptions.length} assumptions`);
if (unsevered.length > 0) console.log(`  ${unsevered.length} edge(s) severed by nothing`);
if (orphanKinds.length > 0) console.log(`  ${orphanKinds.length} change kind(s) sever nothing`);
